### PR TITLE
zapier convert: Generate different search code based on scripting

### PR DESCRIPTION
**Pull request by eliangcs**

### CODE REVIEW

**Comment by eliangcs** [comment]
@BrunoBernardino just pushed ed89147 the cover all the combinations of `search` and `read_resource` scripting methods. If you prefer, you can review it first. Or you can wait for me to add support for `custom_search_fields` methods.

**Comment by BrunoBernardino** [comment]
I'll review and test tomorrow!

**Comment by eliangcs** [comment]
@BrunoBernardino pushed fd42736 to fix `scripting` import error and d18a8ae to use labels for test captions.

**Comment by BrunoBernardino** [comment]
All looks good and tests passing! Awesome job @eliangcs !

**Pull request merged**
