### PR TITLE
Format markdown for console

### PR DESCRIPTION
**Pull request by FokkeZB**
Saturday morning boredom... formats the docs Markdown for console:

### CODE REVIEW

**Comment by bryanhelmig** [comment]
My only concern is the size of the now required markdown library. However, that is minimized considering it is isolated to the CLI and does not leak into core (which would explode the build).

```
$ weigh msee
Approximate weight of msee:
  Uncompressed: 370 kB
  Minified (uglify): 165 kB
  Minified and gzipped (level: default): 52.5 kB
```

**Comment by FokkeZB** [comment]
There's also [marked-terminal](https://www.npmjs.com/package/marked-terminal), with more options and ~ weight:

```
Approximate weight of marked-terminal:
  Uncompressed: 378 kB
  Minified (uglify): 188 kB
  Minified and gzipped (level: default): 50.6 kB
```

**Comment by xavdid** [comment]
I was thinking about this today and would argue we don't need it. Per the [original spec](https://daringfireball.net/projects/markdown/): 

> The idea is that a Markdown-formatted document should be publishable as-is, as plain text

The presence of the markdown should be self sufficient without needing extra formatting. Text like `**required**` stands out because of the asterisks without needing to actually be bold. 

Also this is totally a personal preference thing so I'll understand if we include formatting anyway. Just want to add my 2¢.

**Comment by FokkeZB** [comment]
@xavdid Surely `***required**` stands out, but you don't see Markdown used in CLI outputs often and if you don't know it's markdown (unlike when you view a MD document, when you know it from the context - filename/viewer) it can be confusing:

**Comment by BrunoBernardino** [comment]
I like the colors, but personally think it can cause more problems (it messes with color blindness, accessibility, etc.).

If this can have an opt-out option (like `--plain` for the non-colorized version) I'm all for it.

**Comment by FokkeZB** [comment]
@BrunoBernardino excellent idea to turn `.zapierrc` into a config file rather than just storing the `deployKey`. That would probably take some reorganization though, since it's tight into `utils/api.js` atm.

**Comment by FokkeZB** [comment]
Closing stale PR. We can circle back once we have bandwidth and maybe tie it into introducing a `~/.zapierrc` config file.

**Pull request closed without merging**
