### PR TITLE
Added GA Tracking

### PR DESCRIPTION
**Pull request by ibolmo**

### CODE REVIEW

**Comment by ibolmo** [comment]
After approval just merge to master, or is there a deploy step for docs?

**Comment by xavdid** [comment]
Good catch @BrunoBernardino! @ibolmo let me know when you've updated it and i'll review then

**Comment by ibolmo** [comment]
@xavdid oops. it's ready :D

**Comment by ibolmo** [comment]
Oh man @BrunoBernardino good catch. I had added the changes to the `lib/**`. Gone ahead and added to `src`. Since you're out @xavdid mind taking another look icims.

**Comment by ibolmo** [comment]
Just tested, and it's working. Will add the other team members to have access. Pending to make some scripts to test which sections are most visited, etc.

**Pull request merged**
