### PR TITLE
Generate shell completions scripts for zapier command

### PR DESCRIPTION
**Pull request by stevemolitor**
@bryanhelmig @bcooksey @benzapier 

Zsh completion script for `zapier` command.

completions

# Usage

Copy `./goodies/_zapier` to a direcctory on your `$fpath`, and restart your shell. For example if you use oh-my-zsh:

`cp ./goodies/_zapier ~/.oh-my-zsh/completions`

# TODO

Write a versions for the plebs who use bash. ;)

### CODE REVIEW

**Comment by bryanhelmig** [comment]
That is awesome @stevemolitor ! 😄

**Comment by bryanhelmig** [comment]
Can we add a section to the README for this? Then I am 👍 on merging.

**Comment by stevemolitor** [comment]
@bryanhelmig _Finally_ added a bash version, and added a section to the README. 

Gonna ping @bcooksey too 'cause he's good at documentation. Feel free to tweak the readme.

**Comment by stevemolitor** [comment]
@bryanhelmig Gonna go ahead and merge this. Has bash, zsh completion scripts, entry in the README. We can regen the completion scripts with `npm run gen-completions` when the commands change.

**Pull request merged**
