### PR TITLE
Updating changelog

### LINKED ISSUE #61: Update the changelog
The `CHANGELOG` seems to be out of date.

Can you keep this in sync with any changes to make it easier to review for potential issues when updating?

### PR DESCRIPTION
**Pull request by BrunoBernardino**
Fixes #61

### CODE REVIEW

**Comment by xavdid** [comment]
going forward, do we want to do something like [this](https://coderwall.com/p/5cv5lg/generate-your-changelogs-with-git-log) to update the changelog as part of the `version` command?

**Comment by BrunoBernardino** [comment]
Great idea! Personally, I like giving the changelog a more human/manual touch, though something like this can happen (forgetting to update it). I'm open to implementing something like that.

**Comment by bcooksey** [comment]
Cool idea. If we combined that with commit squashing I think that would work out well. 

Would there be value in tweaking that command so we can also have the ability to manually write a message when need be?

**Comment by xavdid** [comment]
I believe you can edit the file manually after generation and it won't be
overwritten by future releases (though that probably depends on the tool
used)

~DavidB
[davidbrownman.com]
c: 303.819.0850

**Pull request merged**
