### PR TITLE
chore: migrate to cli-table3

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by eliangcs** [comment]
@DanielRuf thanks for sending this patch and we're sorry for the delay here. It seems the `package-lock.json` is out of sync and you haven't signed the CLA. Can you resolve the conflict and sign the CLA for us to merge your PR? Really appreciate your effort upgrading all the packages using `cli-table3`!

**Comment by DanielRuf** [comment]
> you haven't signed the CLA

I saw no notice or CLA bot. Where can I sign it?

**Comment by eliangcs** [comment]
@DanielRuf sorry, looks like the bot didn't pick up when you pushed a new commit. Now you should see the CLA below or use this link: https://cla-assistant.io/zapier/zapier-platform-cli?pullRequest=327.

**Comment by DanielRuf** [comment]
> sign the CLA

Done.

**Pull request merged**
