### PR TITLE
src/utils/misc: Fix "epxeriencing" -> "experiencing" typo

### PR DESCRIPTION
**Pull request by wking**
From a055940f (#282).

### CODE REVIEW

**Comment by wking** [comment]
[Travis is unhappy][1], with errors like:

```
  1) api
       linkedAppConfigs
         should read a config:
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/travis/build/zapier/zapier-platform-cli/lib/tests/utils/api.js)
```

I expect they are all test flakes unrelated to this typo fix.

[1]: https://travis-ci.org/zapier/zapier-platform-cli/jobs/398023480#L2039

**Comment by xavdid** [comment]
ah, thanks! Yeah, we can ignore the tests. Can you sign the CLA (linked in the github checks or [here](https://cla-assistant.io/zapier/zapier-platform-cli?pullRequest=338)) and then I can merge this?

**Comment by wking** [comment]
> Can you sign the CLA...

Signed.  Glad I'm not on the hook to support this typo fix ;).

**Comment by xavdid** [comment]
It's silly, but our lawyers tell us it's important.

Appreciate your patience. 😀

**Comment by wking** [comment]
> Appreciate your patience.

Happy to help, even just a little.  Get them to work on #318 next ;).

**Pull request merged**
